spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5434/store
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data-dev.sql

payment-service:
  base-url: http://localhost:8081